### ISSUE TITLE
Implement V6 ...

### ISSUE THREAD

**Issue by przygienda** [brunorijsman/rift-python#7]
Just fixed the AWS not doing IPv6 LIE multicast and here is the finding:

* Linux is funky because it does NOT support multicast on loopback on many releases and hence I couldn't bring up a LIETX socket. Generally, it's not very 
     clear WHICH interface linux picks for multicast (there is no v6 multicast interface bind
     on the send side) so results may be still random. 
* I solved the problem by picking loopback for v6 multicast if it supports it & otherwise any interfaces that has multicast & v6 addresses. This will work fine on one outgoing interface with v6 but may lead to your and my implementation picking different interfaces to communicate unless we have some common strategy (or just disallow that) ...

**Comment by brunorijsman** [comment]
IPv6 is now fully implemented:
* Sending and receiving LIEs using IPv6
* Flooding (TIEs/TIDEs/TIREs) using IPv6
* SPF (resolve v4 prefixes to v4 next-hops, and v6 prefixes to v6 next-hops)
* Install v6 routes in kernel
